---
- hosts: target
  tasks:
    - name: Install wget, zip, unzip, yum-utils through Yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - zip
        - unzip
        - epel-release
        - yum-utils
      become: yes