---

- hosts: target
  vars:
    hats_env: "/opt/hats"
    py:
      rqms_url: 'https://raw.githubusercontent.com/younglim/hats-ci/master/install-list/pip-install-list.txt'
      temp_dir: "/tmp/{{ansible_user_id}}/ansible"
      filename: "pip-install-list.txt"

  tasks:
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: latest
      become: yes

    - name: Create hats directory
      file:
        path: "{{ hats_env }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        recurse: yes
      become: yes

    - name: Create hats virtualenv
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: --upgrade
        virtualenv: "{{ hats_env }}"
      with_items:
      - pip
      - setuptools
      - python-xlib
      notify: Source hats env

    - name: Append hats env activation to bashrc
      lineinfile:
        path: ~/.bashrc
        state: present
        line: source {{ hats_env }}/bin/activate
      notify: Source bashrc

    - name: Install functools
      shell: ". {{ hats_env}}/bin/activate && easy_install functools"

    - name: Download pip-install-list.txt
      get_url:
        url: "{{ py.rqms_url }}"
        dest: "{{ py.temp_dir }}/{{ py.filename }}"

    - name: Install the packages specified in pip-install-list.txt in hats env
      pip:
        requirements: "{{ py.temp_dir }}/{{ py.filename }}"
        state: present
        virtualenv: "{{ hats_env }}"

    - name: Remove pip-install-list.txt
      file:
        path: "{{ py.temp_dir }}/{{ py.filename }}"
        state: absent

  handlers:
    - name: Source bashrc
      shell: source ~/.bashrc

    - name: Source hats env
      shell: source "{{ hats_env }}"/bin/activate