---

- hosts: target

  tasks:
    - name: Remove all global npm packages that aren't npm itself
      shell: "npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\\/npm$/ {print $NF}' | xargs npm -g rm"
    
    - name: Reinstall appium globally
      npm:
        name: appium
        global: yes
        state: present
