---

- hosts: target
  vars:
    hats_env: "/opt/hats"

  tasks:
    - name: Install virtualenv
      pip: 
        name: virtualenv
        state: latest
      become: yes

    - name: Create hats directory
      file:
        path: "{{ hats_env }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        recurse: yes
      become: yes

    - name: Create hats virtualenv
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: --upgrade
        virtualenv: "{{ hats_env }}"
      with_items:
      - pip
      - setuptools
      - python-xlib
      notify: Source hats env

    - name: Append hats env activation to bashrc
      lineinfile:
        path: ~/.bashrc
        state: present
        line: source {{ hats_env }}/bin/activate
      notify: Source bashrc
  
  handlers:
    - name: Source bashrc
      shell: source ~/.bashrc

    - name: Source hats env
      shell: source "{{ hats_env }}"/bin/activate