---

- hosts: target

  tasks:
    - name: Install xvfb through Yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - xorg-x11-fonts-Type1
      - xorg-x11-fonts-75dpi
      - xorg-x11-server-Xvfb
      become: yes

    - name: Create Xvfb start-stop script
      become: yes
      blockinfile:
        path: /opt/xvfb
        create: yes
        state: present
        mode: +x
        block: |
          #!/bin/bash

          #chkconfig: 345 95 50
          #description: Starts xvfb on display 99
          if [ -z "$1" ]; then
          echo "`basename $0` {start|stop}"
            exit
          fi

          case "$1" in
          start)
            /usr/bin/Xvfb :99 -screen 0 1280x1024x24 &> /var/log/xvfb.log &
          ;;

          stop)
            killall Xvfb
          ;;
          esac

    - name: Append script to configure and run xvfb to bashrc
      blockinfile:
        path: ~/.bashrc
        state: present
        block: |
          sudo /opt/xvfb start
          export DISPLAY=:99