---
- hosts: target
  vars:
    sdk:
      url: 'https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip'
      perm_dir: "/opt/android-sdk"
      zipfilename: "sdk-tools-linux-3859397.zip"
    android:
      build_tools: 'build-tools;27.0.3'
      sys_image: 'system-images;android-27;google_apis;x86'
      platform_tools: 'platform-tools'

  tasks:
    - name: Install Java through Yum
      yum:
        name: java
        state: present
      become: yes
  
    - name: Make new /opt/android-sdk/ directory
      file:
        path: "{{ sdk.perm_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        recurse: yes
      become: yes

    - name: Download Android SDK zipped repo to /opt/android-sdk
      get_url:
        url: "{{ sdk.url }}"
        dest: "{{sdk.perm_dir}}/{{sdk.zipfilename}}"

    - name: Unzip SDK repo
      unarchive:
        src: "{{sdk.perm_dir}}/{{sdk.zipfilename}}"
        dest: "{{sdk.perm_dir}}"
        remote_src: yes

    - name: Remove SDK zipped repo
      file:
        path: "{{sdk.perm_dir}}/{{sdk.zipfilename}}"
        state: absent
      become: yes

    - name: Set Environment Variable for ANDROID_SDK_ROOT, ANDROID_HOME, ANDROID_SDK_HOME and PATHs
      lineinfile:
        path: ~/.bashrc
        line: "{{ item }}"
        state: present
      with_items:
        - 'export ANDROID_SDK_ROOT=/opt/android-sdk'
        - 'export ANDROID_HOME=/opt/android-sdk'
        - 'export ANDROID_SDK_HOME=/opt/android-sdk'
        - 'export PATH=$ANDROID_HOME/platform-tools:$PATH'
        - 'export PATH=$ANDROID_HOME/tools:$PATH'
        - 'export PATH=$ANDROID_HOME/tools/bin:$PATH'

    - name: Source bashrc
      shell: source ~/.bashrc

    - name: Create /opt/android-sdk/.android directory
      file:
        path: "{{ sdk.perm_dir }}/.android"
        state: directory

    - name: Touch repositories.cfg in .android directory
      file:
        path: "{{ sdk.perm_dir }}/.android/repositories.cfg"
        state: touch

    - name: Say yes to all SDK licenses
      shell: yes | sdkmanager --licenses

    - name: Install Android build tools
      shell: sdkmanager {{ android.build_tools|quote }} {{ android.sys_image|quote }} {{ android.platform_tools|quote }} 