---
- hosts: target
  vars:
    rvm:
      url: "https://get.rvm.io"
      temp_installer_path: "/tmp/rvm_installer.sh"

  tasks:
    - name: Install autoconf, automake, bison, readline etc through Yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - autoconf
      - automake
      - bison
      - gcc-c++
      - libffi-devel
      - libtool
      - readline-devel
      - sqlite-devel
      - libyaml-devel
      - openssl-devel
      - git
      become: yes

    - name: Import keys for RVM from GPG
      command: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"

    - name: Download and run RVM installer
      shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby
      register: rvm_result

    - name: Append source rvm to bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'source ~/.rvm/scripts/rvm'
        state: present
      notify: Source bashrc

    - name: Reboot VM to complete RVM installation
      shell: ( sleep 3 && /sbin/reboot & )
      async: 0
      poll: 0
      become: yes

    - name: Wait for server to complete reboot. This will take a while ...
      local_action: wait_for
      args:
        host: target
        delay: 15
        timeout: 150
        state: started
      become: false

    - name: Install ruby-head with RVM
      shell: rvm install ruby-head
      notify: Remove rvm installer

  handlers:
    - name: Source bashrc
      shell: source ~/.bashrc

    - name: Remove rvm installer
      file:
        path: "{{ rvm.temp_installer_path }}"
        state: absent