---

- hosts: target

  tasks:
    - name: Yum install wget, zip, unzip
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - zip
        - unzip
        - epel-release
      become: yes
      