---

- hosts: target

  tasks:
    - name: Install ant and maven through Yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - ant
      - maven
      become: yes

    - name: Install gradle through linuxbrew
      homebrew:
        name: gradle
        state: present