---

- hosts: target

  tasks:
    - name: Appium dependencies
      yum:
        name: gcc-c++
        state: present
      become: yes

    - name: Install Appium
      npm:
        name: appium
        global: yes
        state: present

    - name: Create Appium start-stop script
      become: yes
      blockinfile:
        path: /opt/appium
        create: yes
        state: present
        mode: +x
        block: |
          #!/bin/bash

          #chkconfig: 345 95 50
          #description: Starts appium
          if [ -z "$1" ]; then
          echo "`basename $0` {start|stop}"
            exit
          fi

          case "$1" in
          start)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            appium &> ~/appium.log &
          ;;

          stop)
            killall -r "^node"
          ;;
          esac

    - name: Append script to configure and run appium to bashrc
      lineinfile:
        path: ~/.bashrc
        state: present
        line: /opt/appium start