---

- hosts: mgmt
  become: yes
  gather_facts: false

  tasks:

  - name: Generate host private key
    user:
      name: vagrant
      generate_ssh_key: yes
      ssh_key_file: /home/vagrant/.ssh/id_rsa
      ssh_key_type: rsa
      state: present

  - name: save public key to known_hosts
    known_hosts:
      name: target
      key: "{{ lookup('pipe', 'ssh-keyscan target') }}"
      path: /home/vagrant/.ssh/known_hosts
      state: present

  - name: install ssh key
    authorized_key: user=vagrant key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" state=present
    become: yes
    remote_user: vagrant